### ISSUE TITLE
Add ability to remove a winner

### ISSUE THREAD

**Issue by jaredhasenklein** [Nexus-for-FRC/Nexus#14]
If an incorrect winner is selected during playoff matches, there is a dropdown to change the winner, but not remove it. If a winner is accidentally selected before results are posted, there is not a great way to undo that action.

**Comment by eforbes** [comment]
Unfortunately, undoing winning selection is complex since the system also progresses alliances to the next match(es) and sends notifications.

I'm much more interested in preventing this error case from occurring all together- if you have any suggestions for changes that would have prevented the mistaken winner selection please let me know

**Comment by jaredhasenklein** [comment]
Makes sense, let me think on it. Tl;dr, handing people the lead queueing tablet during a bathroom break is a bad call, evidently. I suppose that the current popups (not enough time has passed for this action to make sense) are good, but maybe should have a more significant error check than pressing a button (like requiring a checkbox or entering text and then pressing a button. 

I guess what is like in a feature wouldn't really undo everything, but would at least remove the wrong teams from the next match. It wouldn't have to reverse the advancement of match flow.

**Comment by eforbes** [comment]
For now, I've updated the dialog to be a little scarier looking and require an additional tap to confirm

**Comment by eforbes** [comment]
This option is now available after a winner has been set on a match:

![frc nexus_en_event_demo6963_queue(iPhone 14 Pro Max)](https://github.com/Nexus-for-FRC/Nexus/assets/2548822/c9b9d4d1-8250-4c13-9e3f-bc5365ac89df)
