### ISSUE TITLE
Turkish Translation is completed

### ISSUE THREAD

**Issue by antlionguard** [Nexus-for-FRC/Nexus#16]
Hi,

I completed the translations into Turkish. Can you publish the translations? I want to see how it looks with the demo event and quickly fix any errors.

**Comment by eforbes** [comment]
Thanks for contributing translations!

You can review the test version of the application in Turkish here: https://staging.frc.nexus/tr-TR

Let me know if you have any questions. When you are done with your review let me know and I will push the translations to production and they will be available for all users.

**Comment by antlionguard** [comment]
<img width="1589" alt="image" src="https://github.com/Nexus-for-FRC/Nexus/assets/26603638/83d03d96-72bb-4ed6-8dd7-7dad729614e1">

This screen and header does not have any translation. I think that's not coded yet. Thats not urgent for us. Because Usually our volunteers are enough English enough to understand these screens. 

Also, I could not test the instant operation of the matches at the demo event. Do we have a chance to try these screens and Event Display? But in general, we're sure of the accuracy of translations.

**Comment by eforbes** [comment]
Only team facing interfaces are currently eligible for translation- all volunteer facing screens will be mostly English.

You can view the team dashboard by scanning one of the QR codes on the team handouts PDF ([top right printer icon](https://staging.frc.nexus/tr-TR/event/demo0874/manage/teams)).

[The event pit display can be viewed here](https://staging.frc.nexus/tr-TR/event/demo0874/display/pit).

To queue some matches in your demo event, visit [this page](https://staging.frc.nexus/tr-TR/event/demo0874/manage/queue) and tap "queue first matches".

**Comment by antlionguard** [comment]
hello again. i did some translation fixes. Could you please publish release for new changes?

**Comment by eforbes** [comment]
The latest translations are now live on the test environment. You may need to refresh the page and wait up to 30 seconds before the new changes are displayed

**Comment by antlionguard** [comment]
<img width="253" alt="image" src="https://github.com/Nexus-for-FRC/Nexus/assets/26603638/46f313d4-41ab-4125-af5a-531e491c9a9c">
can we change 12h time to 24h in turkish? In turkey we use 24h system generally.

**Comment by eforbes** [comment]
It should now localize all queuing times in the test environment- thanks for pointing that out

**Comment by antlionguard** [comment]
hi it's me again :d 

there difference between these hours. we are in the gmt +3 time zone. the time is top of the accordion is right time. Can you check it? 
<img width="686" alt="Screenshot 2024-02-29 at 19 39 37" src="https://github.com/Nexus-for-FRC/Nexus/assets/26603638/1774db44-b649-4187-b4d2-108b6fac52c6">  

In addition, can you write "Türkçe" instead of "Turkish" for teams which are not know english.

You can also publish the translation when you are ready. The translations look good for us. In connection with this, when you publish the Turkish translations, we are thinking of printing the nexus brochures and placing them in the teams' files. Will it cause any problems if we prepare nexus brochures for the Istanbul Regional in the 2nd week? Are there any cases where QR codes become dysfunctional?

We are grateful for your answers and solutions <3

**Comment by eforbes** [comment]
Are you still able to reproduce the time zone issue? Does it reproduce on multiple devices (phone & computer)? If so, can you provide the following details:
- Browser
- Device time zone setting

The translations will be deployed Sunday evening US time. QR codes are stable, so printing them early is fine. If you wait until after I release the translations then handouts will be bilingual (print double sided, english will be on one side/turkish on the other)

**Comment by antlionguard** [comment]
> Are you still able to reproduce the time zone issue? Does it reproduce on multiple devices (phone & computer)? If so, can you provide the following details:
> 
>     * Browser
> 
>     * Device time zone setting
> 
> 
> The translations will be deployed Sunday evening US time. QR codes are stable, so printing them early is fine. If you wait until after I release the translations then handouts will be bilingual (print double sided, english will be on one side/turkish on the other)

Oh my bad. i'm using timezone spoof extension and that extension caused that. There was no problem. Apologies

**Comment by eforbes** [comment]
The Turkish translation is now live. Thanks again!
