### ISSUE TITLE
Usability: Inspection "skip pnuematics" undo

### ISSUE THREAD

**Issue by nzrutman** [Nexus-for-FRC/Nexus#20]
If an inspector accidentally clicks "skip pneumatics" during the inspection process, all pneumatics items are marked "NA" and no longer shown as TBD (good). However, if "skip pneumatics" is clicked accidentally, there's no easy way to undo it - you have to go to each individual item to reset it. The remainder are all still "NA", so it's the inspector's burden to hunt them all down (including one in the electrical section) because they are not TBD.
Desired behavior: if any pneumatics item is reset, all pneumatics in NA states should be reverted to uninspected/TBD.

**Comment by eforbes** [comment]
Thanks for the report. This will be fixed in the next release (exact date currently unknown)
