### ISSUE TITLE
Usability: Inspection green checked-off box is not cleared on mobile/iOS

### ISSUE THREAD

**Issue by nzrutman** [Nexus-for-FRC/Nexus#21]
When proceeding through an inspection checklist on mobile (at least iOS), checking off an item turns the button green and moves on to the next item. However, the button stays green on the next screen, giving the false impression that the next item has been checked. Inspector has to re-check what apparently is an already-checked button.
On laptop/browser this is not the case; the button (on the next screen) turns green only if the mouse hovers over it.

**Comment by eforbes** [comment]
Thanks for the report. This will be fixed in the next release (exact date currently unknown)
