### ISSUE TITLE
Feature Request: Metric system support

### ISSUE THREAD

**Issue by antlionguard** [Nexus-for-FRC/Nexus#22]
Helloo i have live feedback from our robot inspectors from Türkiye. They said we use metric system measurements and weights and we cannot enter metric measurements. Can you add metric measurements? And How long it takes?

**Comment by eforbes** [comment]
Thanks for the suggestion- entry of weights in metric is not supported yet- I'll consider that for next year.

All measurements in the checklist though should also be displayed in metric, in the same format that the official checklist does.

**Comment by eforbes** [comment]
Inspectors can now toggle between lb & kg by tapping the units next to the weight input fields.

![conversion](https://github.com/user-attachments/assets/2649b0ea-c4b6-4dda-96f4-cc96328bab27)
