### ISSUE TITLE
Feature Request: Inıtial Inspection Status

### ISSUE THREAD

**Issue by antlionguard** [Nexus-for-FRC/Nexus#23]
Hello again. I have another live feedback our lri and head ref. They want to see initial inspection status for practice matches. Because you know if team is not passed initial inspection they not allowed to join practice matches.

**Comment by eforbes** [comment]
Thanks for the request. I don't think this is an official requirement anymore, but if you have a rule number please add it here.

The only reference I found related to this was in the driver's meeting script:

> Robots must have some kind of bumper and not pose a 
danger to people or other robots to be in any practice matches

This doesn't need to be determined by an inspector though, field staff can make this determination
