### ISSUE TITLE
Feature Request: Slide to unlock for prevent accidental winner select

### ISSUE THREAD

**Issue by antlionguard** [Nexus-for-FRC/Nexus#24]
Hellooo, we noticed something during the competition. A friend of ours accidentally selected a winner before the playoff match was even played, and therefore the queue operations were processed incorrectly. Maybe it would be better to design a UI that prevents accidental presses. We can then unlock the winner bar at the bottom with a like slide to unlock option and then select the winner.

**Comment by eforbes** [comment]
There is a dialog that will show if a user tries to select a winner (or do any queuing action) within 4 minutes of the previous action:

![image](https://github.com/Nexus-for-FRC/Nexus/assets/2548822/7fc79798-2682-4993-9e3c-348ebb34f68c)


There's also a "Cancel" button that is shown for at least 5 seconds after selecting a winner:

![image](https://github.com/Nexus-for-FRC/Nexus/assets/2548822/000242df-e228-49c2-bd32-27e0ee5d0adf)

Were either of these features useful in this case?

**Comment by eforbes** [comment]
This has been implemented and enabled by default for all touchscreen devices:

![staging frc nexus_en_event_demo8043_queue(iPhone 14 Pro Max) (2)](https://github.com/Nexus-for-FRC/Nexus/assets/2548822/179f9839-ce55-4fbf-aa33-b70e779848ea)


I'll collect feedback at the next few offseasons to ensure it doesn't cause any unexpected issues, but for now I like it. Thanks for the suggestion!

**Comment by antlionguard** [comment]
that was awesome. thanks for your effort <3
