### ISSUE TITLE
Allow arbitrary team notification webhooks

### ISSUE THREAD

**Issue by adamsong** [Nexus-for-FRC/Nexus#26]
For teams who use something other than slack/discord for communication, allow inputting a webhook URL that just sends a request in a predefined format, (A POST request with a string body would be sufficient, but json with more detail could also be used) that allows teams to define their own handler. I feel like a lot of teams can handle listening for this, and it would allow teams to send the messages to arbitrary platforms.

**Comment by eforbes** [comment]
Take a look at the new Nexus API!

[frc.nexus/api/v1/docs](https://frc.nexus/api/v1/docs)

Please file additional issues if there is further data or functionality you would like in the API.
