### ISSUE TITLE
Add team/event specific webhook

### ISSUE THREAD

**Issue by adamsong** [Nexus-for-FRC/Nexus#27]
I'm liking what the API can do right now, and I can make it work as is, but I was hoping for the ability to add a webhook on the same page as the slack/discord/text notifications, and get the same filtering that those do, so I'm not sieving through as much data.

Additionally, the event key, is that the same key as used elsewhere (TBA/FRCEvents) or is it unique to nexus?

**Comment by eforbes** [comment]
Thanks for the feedback- a team specific filter will be available soon, but it will also be configured on the API page.

For official events, the Nexus event key is the same as the FRC API (which except for cmp divisions is also the same as TBA).

Offseasons are less consistent and frequently have different event keys on the FRC API and TBA and could match either depending on how the event was registered for Nexus.

**Comment by eforbes** [comment]
Added in API v1.1.0
