### ISSUE TITLE
Feature Request: Reinspection status

### ISSUE THREAD

**Issue by hesterliu** [Nexus-for-FRC/Nexus#29]
There is currently no capability for checking off reinspections on the inspection dashboard.  Would you be able to integrate playoff reinspection similar to the current inspection dashboard (not started, in progress, complete)? It would also be useful to include the original weighting of the robots and a space to insert their new weight on the same screen for comparison purposes. Thanks.

**Comment by eforbes** [comment]
I just added a simple playoff reinspection process building off the new general reinspection feature.

From the documentation: 
> All teams can be flagged for a playoff reinspection with a single tap on the LRI requests page. Tap this button on the last day of the event, prior to the last round of qualifications. Every team that completed their initial inspection will be moved to the "Waiting for inspector" section. Teams will be sorted chronologically by their last qualification match, so they can be quickly processed in order.

No specific weight steps are built in- I expect the way weights are handled will be slightly different in the 2025 inspection checklist and that will hopefully solve this problem.
