### ISSUE TITLE
Feature Request: Custom inspection checklist items

### ISSUE THREAD

**Issue by hesterliu** [Nexus-for-FRC/Nexus#30]
It would be good to have the ability to add custom inspection checklist items to help clarify or add robustness to the inspection process, especially for new inspectors or during the offseason. This was a personal observation when, during a recent offseason, many pre-rookie teams had passed inspection with uncovered battery leads or unimaged radios as this was not an explicit item on the checklist. While these things are usually implied, some newer teams, and newer inspectors alike, may not keep that constantly on their mind as something to check. The ability to add custom items will help with newer teams and inspectors identify these as issues and important items that should be addressed.

**Comment by eforbes** [comment]
I think it's very unlikely the checklist in Nexus will ever deviate non-trivially from the official published checklist.

Feel free to provide your feedback to the chief LRIs to ensure the official checklist covers safety critical items.
