### ISSUE TITLE
Feature Request: Add “en route” queue state

### ISSUE THREAD

**Issue by noahlinton** [Nexus-for-FRC/Nexus#32]
For venues with long distances between pits, it would be nice to have an additional queue state that queuers in the pits can indicate teams have left the pits and are heading to the field. This would have been useful at STEMley/Overtime. We were using walkie-talkies to communicate this info but it was not ideal. Long walk and short turn around times were the main issues here. Maybe it’s a feature that is enabled in settings so it’s only there if your venue requires it?

Open to alternative solutions if there are suggestions on other ways to use NEXUS as-is to solve this problem.

**Comment by eforbes** [comment]
My general opinion on this is that queuers shouldn't need to know whether teams are on the way or not and that this tracking would add unnecessary complexity.

Ultimately it is just the queuers responsibility to notify the teams when they should be at the field, and it's up to the teams to actually arrive at the field by the right time (or not, if they don't want to).

Also in my proposed queuing model, pit queuers don't exist so there would not be anyone there to update this state.
